from pytube import YouTube
while True:
    print('''
    .:........................:::....:......:::::.::::::::::...::::::::::.::.::::::......:..............:.                        
    ...:5PPPP^.?GGGB?...JBGGBBBBB!.........~B#B#G:^B#BBB###BB5!.:G#########!.G####BBBBBP::^PGGGPPPPY:.....                        
    ...^@@@@@^.5@@@@Y..:#@@@@@@@@5.........!@@@@&:^@@@@@P5&@@@@~:&@@@@#BBBB!.PBB##@@@@@B..!@@@@@@@@&^.....                        
    ...^&@@@&^.5@@@@Y..~&@@@P#@@@B.........~@@@@#:^&@@@&~:G@@@@?:&@@@@!........:.?@@@@@7..J@@@@G@@@@!.....                        
    ...^&@@@&^.5@@@@Y..7@@@@7P@@@@~........!@@@@&:~&@@@@&&@@@&5:^&@@@@BPP5Y:....?@@@@@7...P@@@&?@@@@J.....                        
    .:.^&@@@@BB&@@@@Y..Y@@@&^?&&&&7.~7??J!.~####B:^B#B#BJJBBBBJ.:B#######&#^...?@@&@&7...:#@@@B~&@@@P...:.                        
    .:.^#&&&&&&####&J.:P#BBP.~BBB#Y.J####J.~#BB#B:^BBBBB^:B#B#B^:B#BBB!.::^:..?##B#B!....~###&5.B@@@B:....                        
    ...^BBBBB7^Y#BB#J.^B#B#GY5#BB#G:?#BB#5^?####P:^B###B^^B###B^:B#BB#7^^::::J##B#G~.....7BBBB7.JBBBG^....                        
    ...^B#B#B^.J#BB#J.7#BBBBGPG####!^PB######BPJ^.^GBBBG^:GBBBG::B#######BB?7##BBB?~~^::.5#BB#57Y#BBB!....                        
    ...^B#B#B^.Y#BB#J.Y####!..?BGGP7.:~!777!~^....:^^^^^::^^^^^.:~!!77??YYP77BBB#####BB?:G#BBB###BBB#?....                        
    ...^B#B#B^.Y####J.5GPYJ:..:^::..:.........~~^^~~:~^^~^~~^^^^............::^^!!?JYPG?~####G!7JBBB#Y....                        
    ...^B###B^.JPYJ7^.::.............       ::!~~~~~^~!!!~!!~!~!::       .............:::!7J5J...G###G:...                        
    ...^BG5J7:.::..........                 .::::::::::::::::::::.                 ............:.7YPGB^...                        
    ...:^:.........                                                                         ........:^:...                        
    .:.......         
''')

    print ('''
==============================================
[developer] => Hajreza_R [developer_Youtube channel] => https://tinyurl.com/y9karfwv ) 
[developer_Instagram ] => https://tinyurl.com/ytn3rkwx
==============================================
''')
    link = input("please enter your link: ")
    video = YouTube(link)
    stream = video.streams.get_highest_resolution()
    stream.download()
    print("ok download is compleate")
    